### PR TITLE
For Welcome Page - Fixed Indentation on HTML & CSS

### PR DESCRIPTION
**Pull request by sarinalalria**

### CODE REVIEW

**Comment by zeshengchen** [comment]
I will approve this pull request. But I cannot see why it needs to close the previous pull request and create a new one. It can simply fix all issues in the previous pull request, right?

**Review by zeshengchen — APPROVED** [review]

**Comment by YiShianLiu** [comment]
Sorry, I hit the wrong button, still not familiar with github.
I approve the pull request.

**Review by nscheiber — COMMENTED** [review]
I approve the changes.

**Review by Sinclair198 — COMMENTED** [review]
I approve of the changes

**Comment by zeshengchen** [comment]
Please move the two files under root folder into the corresponding folders.

**Comment by sarinalalria** [comment]
They have been moved into the corresponding folders. Thank you professor.

**Pull request merged**
